/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import entidades.Autor;
import entidades.Libro;
import entidades.LibroElectronico;
import entidades.LibroImpreso;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import operaciones.OperacionesLibro;

/**
 *
 * @author Alex
 */
public class JFrameNuevoLibro extends javax.swing.JFrame {
    OperacionesLibro oper;
    /**
     * Creates new form JFrameNuevoLibro
     */
    public JFrameNuevoLibro() {
        initComponents();
        ///VISIBLE EL PANEL DEL LIBRO IMPRESO///
        jPanel_LIBRO_IMPRESO.setVisible(false);
        jPanel_LIBRO_DIGITAL.setVisible(false);
        ///TEXT FIELD DE INTERACTIVO DESHABILITADO///
        jTextField_Es_interactivo.setEnabled(false);
        oper=new OperacionesLibro();
        jRadioButton_DURA.setSelected(true);
        this.setLocationRelativeTo(null);
        jComboBoxTipo.setSelectedIndex(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_TIPO_PASTA = new javax.swing.ButtonGroup();
        jLabelTipo = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox();
        jLabelISBN = new javax.swing.JLabel();
        jTextFieldISBN = new javax.swing.JTextField();
        jLabelTITULO = new javax.swing.JLabel();
        jTextFieldTITULO = new javax.swing.JTextField();
        jLabelNUMERO_DE_PAGINAS = new javax.swing.JLabel();
        jSpinner_NUMERO_DE_PAGINAS = new javax.swing.JSpinner();
        jLabel_AUTOR_PRINCIPAL = new javax.swing.JLabel();
        jComboBox_AUTOR_PRINCIPAL = new javax.swing.JComboBox();
        jPanel_LIBRO_IMPRESO = new javax.swing.JPanel();
        jLabel_TIPO_PASTA = new javax.swing.JLabel();
        jRadioButton_DURA = new javax.swing.JRadioButton();
        jRadioButton_SUAVE = new javax.swing.JRadioButton();
        jLabelPasta_Seleccionada = new javax.swing.JLabel();
        jPanel_LIBRO_DIGITAL = new javax.swing.JPanel();
        jLabel_TAMAÑO_ARCHIVO = new javax.swing.JLabel();
        jSpinner_TAMAÑO_ARCHIVO = new javax.swing.JSpinner();
        jCheckBox_ES_INTERACTIVO = new javax.swing.JCheckBox();
        jTextField_Es_interactivo = new javax.swing.JTextField();
        jButton_GUARDAR = new javax.swing.JButton();
        jButton_CANCELAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LIBRO");

        jLabelTipo.setText("TIPO");

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-------------------------", "LIBRO IMPRESO", "LIBRO ELECTRONICO", " " }));
        jComboBoxTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoItemStateChanged(evt);
            }
        });
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });

        jLabelISBN.setText("ISBN");

        jTextFieldISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldISBNKeyTyped(evt);
            }
        });

        jLabelTITULO.setText("TITULO");

        jLabelNUMERO_DE_PAGINAS.setText("NUMERO DE PAGINAS");

        jSpinner_NUMERO_DE_PAGINAS.setModel(new javax.swing.SpinnerNumberModel(10, 10, 1000, 1));

        jLabel_AUTOR_PRINCIPAL.setText("AUTOR PRINCIPAL");

        jComboBox_AUTOR_PRINCIPAL.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----------", "AUTOR 1", "AUTOR 2", "AUTOR 3", "AUTOR 4" }));

        jPanel_LIBRO_IMPRESO.setBackground(new java.awt.Color(255, 255, 153));
        jPanel_LIBRO_IMPRESO.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Libro Impreso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N

        jLabel_TIPO_PASTA.setText("TIPO DE PASTA");

        buttonGroup_TIPO_PASTA.add(jRadioButton_DURA);
        jRadioButton_DURA.setText("DURA");
        jRadioButton_DURA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton_DURAStateChanged(evt);
            }
        });

        buttonGroup_TIPO_PASTA.add(jRadioButton_SUAVE);
        jRadioButton_SUAVE.setText("SUAVE");
        jRadioButton_SUAVE.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton_SUAVEStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel_LIBRO_IMPRESOLayout = new javax.swing.GroupLayout(jPanel_LIBRO_IMPRESO);
        jPanel_LIBRO_IMPRESO.setLayout(jPanel_LIBRO_IMPRESOLayout);
        jPanel_LIBRO_IMPRESOLayout.setHorizontalGroup(
            jPanel_LIBRO_IMPRESOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LIBRO_IMPRESOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_TIPO_PASTA)
                .addGap(31, 31, 31)
                .addGroup(jPanel_LIBRO_IMPRESOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_LIBRO_IMPRESOLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelPasta_Seleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_LIBRO_IMPRESOLayout.createSequentialGroup()
                        .addComponent(jRadioButton_DURA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton_SUAVE)
                        .addGap(46, 46, 46))))
        );
        jPanel_LIBRO_IMPRESOLayout.setVerticalGroup(
            jPanel_LIBRO_IMPRESOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LIBRO_IMPRESOLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel_LIBRO_IMPRESOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TIPO_PASTA)
                    .addComponent(jRadioButton_DURA)
                    .addComponent(jRadioButton_SUAVE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPasta_Seleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_LIBRO_DIGITAL.setBackground(new java.awt.Color(255, 255, 153));
        jPanel_LIBRO_DIGITAL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Libro Digital", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N

        jLabel_TAMAÑO_ARCHIVO.setText("TAMAÑO DE ARCHIVO");

        jSpinner_TAMAÑO_ARCHIVO.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.5f), Float.valueOf(0.3f), Float.valueOf(100.0f), Float.valueOf(0.5f)));

        jCheckBox_ES_INTERACTIVO.setText("ES INTERACTIVO?");
        jCheckBox_ES_INTERACTIVO.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox_ES_INTERACTIVOStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel_LIBRO_DIGITALLayout = new javax.swing.GroupLayout(jPanel_LIBRO_DIGITAL);
        jPanel_LIBRO_DIGITAL.setLayout(jPanel_LIBRO_DIGITALLayout);
        jPanel_LIBRO_DIGITALLayout.setHorizontalGroup(
            jPanel_LIBRO_DIGITALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LIBRO_DIGITALLayout.createSequentialGroup()
                .addGroup(jPanel_LIBRO_DIGITALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_LIBRO_DIGITALLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel_TAMAÑO_ARCHIVO))
                    .addGroup(jPanel_LIBRO_DIGITALLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBox_ES_INTERACTIVO)))
                .addGap(66, 66, 66)
                .addGroup(jPanel_LIBRO_DIGITALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinner_TAMAÑO_ARCHIVO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Es_interactivo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel_LIBRO_DIGITALLayout.setVerticalGroup(
            jPanel_LIBRO_DIGITALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LIBRO_DIGITALLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_LIBRO_DIGITALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TAMAÑO_ARCHIVO)
                    .addComponent(jSpinner_TAMAÑO_ARCHIVO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_LIBRO_DIGITALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox_ES_INTERACTIVO)
                    .addComponent(jTextField_Es_interactivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_GUARDAR.setBackground(new java.awt.Color(153, 153, 255));
        jButton_GUARDAR.setText("GUARDAR");
        jButton_GUARDAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_GUARDARMouseClicked(evt);
            }
        });

        jButton_CANCELAR.setBackground(new java.awt.Color(153, 153, 255));
        jButton_CANCELAR.setText("CANCELAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jButton_GUARDAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_CANCELAR)
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel_LIBRO_IMPRESO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_LIBRO_DIGITAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTipo)
                            .addComponent(jLabelISBN)
                            .addComponent(jLabelTITULO))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldISBN)
                            .addComponent(jTextFieldTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelNUMERO_DE_PAGINAS)
                        .addGap(42, 42, 42)
                        .addComponent(jSpinner_NUMERO_DE_PAGINAS, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel_AUTOR_PRINCIPAL)
                        .addGap(46, 46, 46)
                        .addComponent(jComboBox_AUTOR_PRINCIPAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipo)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelISBN)
                    .addComponent(jTextFieldISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTITULO)
                    .addComponent(jTextFieldTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNUMERO_DE_PAGINAS)
                    .addComponent(jSpinner_NUMERO_DE_PAGINAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_AUTOR_PRINCIPAL)
                    .addComponent(jComboBox_AUTOR_PRINCIPAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jPanel_LIBRO_IMPRESO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_LIBRO_DIGITAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_GUARDAR)
                    .addComponent(jButton_CANCELAR))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jComboBoxTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoItemStateChanged
        // TODO add your handling code here:
        int indiceSeleccionado = jComboBoxTipo.getSelectedIndex();
        if(indiceSeleccionado==1){
            jPanel_LIBRO_IMPRESO.setVisible(true);
            jPanel_LIBRO_DIGITAL.setVisible(false);
        }
        else{
            jPanel_LIBRO_DIGITAL.setVisible(true);
            jPanel_LIBRO_IMPRESO.setVisible(false);
        }
    }//GEN-LAST:event_jComboBoxTipoItemStateChanged

    private void jRadioButton_DURAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton_DURAStateChanged
        // TODO add your handling code here:
        if(jRadioButton_DURA.isSelected()){
            jLabelPasta_Seleccionada.setText(jRadioButton_DURA.getText());
        }
       
    }//GEN-LAST:event_jRadioButton_DURAStateChanged

    private void jRadioButton_SUAVEStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton_SUAVEStateChanged
        // TODO add your handling code here:
           if(jRadioButton_SUAVE.isSelected()){
            jLabelPasta_Seleccionada.setText(jRadioButton_SUAVE.getText());
        }
    }//GEN-LAST:event_jRadioButton_SUAVEStateChanged

    private void jCheckBox_ES_INTERACTIVOStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox_ES_INTERACTIVOStateChanged
        // TODO add your handling code here:
        if(jCheckBox_ES_INTERACTIVO.isSelected())
        {
            jTextField_Es_interactivo.setEnabled(true);
        }
        else{
            jTextField_Es_interactivo.setEnabled(false);
            jTextField_Es_interactivo.setText("");
           
        }
    }//GEN-LAST:event_jCheckBox_ES_INTERACTIVOStateChanged

    private void jButton_GUARDARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_GUARDARMouseClicked

        this.guardarlibro();
    }//GEN-LAST:event_jButton_GUARDARMouseClicked
int contCaracteres=0;
    private void jTextFieldISBNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldISBNKeyTyped
        // TODO add your handling code here:
        Character ch= evt.getKeyChar();
        if(!Character.isDigit(ch) && ch != KeyEvent.VK_BACK_SPACE && ch!=KeyEvent.VK_DELETE){
            JOptionPane.showMessageDialog(this, "solo numeros");
            evt.consume();//consume el evento,por tanto la tecla ya no se tipea (no se dibuja)
        }else { //si es digito
            if(contCaracteres>=13){
                  JOptionPane.showMessageDialog(this, "solo 13 numeros");
                  evt.consume();
            
        }else {
        contCaracteres++;
    }
        
        
    }//GEN-LAST:event_jTextFieldISBNKeyTyped
    }
    public void guardarlibro(){
        //1.Verificaciones y validaciones
        if(jTextFieldISBN.getText().equals("")){
            JOptionPane.showMessageDialog(this, "INGREE EL ISBN");
            return;
        }
        //2.Leer datos del formulario
       String tipo= (String)jComboBoxTipo.getSelectedItem();
       String isbn= jTextFieldISBN.getText();
       String titulo=jTextFieldTITULO.getText();
       int numeropaginas= (int) jSpinner_NUMERO_DE_PAGINAS.getValue();
       String autor=(String) jComboBox_AUTOR_PRINCIPAL.getSelectedItem();
       Autor au = new Autor();
       au.setNombres(autor);
       int tipo2=jComboBoxTipo.getSelectedIndex();
       Libro libro;
       
                    if(tipo2==1){
                      String tipoPasta="";
                      if(jRadioButton_DURA.isSelected()){
                          tipoPasta=jRadioButton_DURA.getText();
                      }else if(jRadioButton_SUAVE.isSelected()){
                          tipoPasta=jRadioButton_SUAVE.getText();
                      }
                      libro = new LibroImpreso(numeropaginas, tipoPasta,isbn,titulo,2019,0,au);
                    
                    }
                    
                    else if(tipo2==2){
                        float tamaño_archivo=(float)jSpinner_TAMAÑO_ARCHIVO.getValue();
                        boolean esinteractivo=jCheckBox_ES_INTERACTIVO.isSelected();
                        String textInteractivo="";
                        if(esinteractivo){
                            textInteractivo=jTextField_Es_interactivo.getText();
                        }  
                        libro = new LibroElectronico(tamaño_archivo,esinteractivo,isbn,titulo,numeropaginas,0,au);
                    }
                    else{
                    libro = new LibroImpreso();
                    }
                    
                     double precio= libro.calcularPrecio();
                     JOptionPane.showMessageDialog(this, "El libro " + libro.toString());
                     JOptionPane.showMessageDialog(this, "El precio del libro es "+ precio);
                   //Guaradar en la coleccion 
                     oper.agregar(libro);
                     oper.guardarEnArchivo(libro);
    }
    
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameNuevoLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_TIPO_PASTA;
    private javax.swing.JButton jButton_CANCELAR;
    private javax.swing.JButton jButton_GUARDAR;
    private javax.swing.JCheckBox jCheckBox_ES_INTERACTIVO;
    private javax.swing.JComboBox jComboBoxTipo;
    private javax.swing.JComboBox jComboBox_AUTOR_PRINCIPAL;
    private javax.swing.JLabel jLabelISBN;
    private javax.swing.JLabel jLabelNUMERO_DE_PAGINAS;
    private javax.swing.JLabel jLabelPasta_Seleccionada;
    private javax.swing.JLabel jLabelTITULO;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabel_AUTOR_PRINCIPAL;
    private javax.swing.JLabel jLabel_TAMAÑO_ARCHIVO;
    private javax.swing.JLabel jLabel_TIPO_PASTA;
    private javax.swing.JPanel jPanel_LIBRO_DIGITAL;
    private javax.swing.JPanel jPanel_LIBRO_IMPRESO;
    private javax.swing.JRadioButton jRadioButton_DURA;
    private javax.swing.JRadioButton jRadioButton_SUAVE;
    private javax.swing.JSpinner jSpinner_NUMERO_DE_PAGINAS;
    private javax.swing.JSpinner jSpinner_TAMAÑO_ARCHIVO;
    private javax.swing.JTextField jTextFieldISBN;
    private javax.swing.JTextField jTextFieldTITULO;
    private javax.swing.JTextField jTextField_Es_interactivo;
    // End of variables declaration//GEN-END:variables
}
