/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import entidades.Autor;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import operaciones.OperacionesAutor;

/**
 *
 * @author Alex
 */
public class JFrameNuevoAutor extends javax.swing.JFrame {
    
    OperacionesAutor opeAutor;
    
    /**
     * Creates new form JFrameNuevoAutor
     */
    public JFrameNuevoAutor() {
        initComponents();
        this.setTitle("AUTOR");
        this.opeAutor = new OperacionesAutor();
    }
     /* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNOMBRE = new javax.swing.JLabel();
        jLabelAPELLDIO = new javax.swing.JLabel();
        jLabelPAISDEORIGEN = new javax.swing.JLabel();
        jTextFieldNOMBRES = new javax.swing.JTextField();
        jTextFieldAPELLIDO = new javax.swing.JTextField();
        jComboBoxPaisOrigen = new javax.swing.JComboBox();
        jButtonGUARDAR = new javax.swing.JButton();
        jButtonCANCELAR = new javax.swing.JButton();
        jButtonVerAutores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelNOMBRE.setText("NOMBRE: ");

        jLabelAPELLDIO.setText("APELLIDO: ");

        jLabelPAISDEORIGEN.setText("PAIS DE ORIGEN: ");

        jComboBoxPaisOrigen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-----------", "ALEMANIA", "ARGENTINA", "CHILE", "ECUADOR", "ESTADOS UNIDOS", "OTRO", " " }));
        jComboBoxPaisOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPaisOrigenActionPerformed(evt);
            }
        });

        jButtonGUARDAR.setText("GUARDAR");
        jButtonGUARDAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGUARDARMouseClicked(evt);
            }
        });
        jButtonGUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGUARDARActionPerformed(evt);
            }
        });
        jButtonGUARDAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonGUARDARKeyPressed(evt);
            }
        });

        jButtonCANCELAR.setText("CANCELAR");
        jButtonCANCELAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCANCELARMouseClicked(evt);
            }
        });

        jButtonVerAutores.setText("Ver Autores");
        jButtonVerAutores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVerAutoresMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jButtonGUARDAR)
                .addGap(74, 74, 74)
                .addComponent(jButtonCANCELAR)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAPELLDIO)
                            .addComponent(jLabelNOMBRE)
                            .addComponent(jLabelPAISDEORIGEN))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNOMBRES)
                            .addComponent(jTextFieldAPELLIDO)
                            .addComponent(jComboBoxPaisOrigen, 0, 203, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButtonVerAutores)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNOMBRE)
                    .addComponent(jTextFieldNOMBRES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAPELLDIO)
                    .addComponent(jTextFieldAPELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPAISDEORIGEN)
                    .addComponent(jComboBoxPaisOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGUARDAR)
                    .addComponent(jButtonCANCELAR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButtonVerAutores)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxPaisOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPaisOrigenActionPerformed
        
    }//GEN-LAST:event_jComboBoxPaisOrigenActionPerformed

    private void jButtonGUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGUARDARActionPerformed

    }//GEN-LAST:event_jButtonGUARDARActionPerformed

    private void jButtonGUARDARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGUARDARMouseClicked
       
        this.guardarAutor();
    }
    public void guardarAutor(){
        //variables que guardan espacio en memoria
        String nombres=jTextFieldNOMBRES.getText();
        String apellidos=jTextFieldAPELLIDO.getText();
        String pais = jComboBoxPaisOrigen.getSelectedItem().toString();
        //crear objetos y darle datos
        Autor autor = new Autor(nombres, apellidos , pais);
        //guardar en la lista de Autores
        opeAutor.agregar(autor);
        JOptionPane.showMessageDialog(this, "GUARDADO CON EXITO");
        this.limpiar();
    }//GEN-LAST:event_jButtonGUARDARMouseClicked

    private void jButtonGUARDARKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonGUARDARKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            this.guardarAutor();
        }
        if(evt.getKeyChar()=='G'){
            this.guardarAutor();
        }
    }//GEN-LAST:event_jButtonGUARDARKeyPressed

    private void jButtonCANCELARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCANCELARMouseClicked
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_jButtonCANCELARMouseClicked

    private void jButtonVerAutoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVerAutoresMouseClicked
        // TODO add your handling code here:
         String autores ="";
         for(Autor au: opeAutor.getLista()){
             autores+="\n " + au.toString();
         }
        JOptionPane.showMessageDialog(this,autores);
    }//GEN-LAST:event_jButtonVerAutoresMouseClicked

    public void limpiar(){
    this.jTextFieldAPELLIDO.setText(" ");
    this.jTextFieldNOMBRES.setText(" ");
    this.jComboBoxPaisOrigen.setSelectedIndex(0);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameNuevoAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameNuevoAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameNuevoAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameNuevoAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameNuevoAutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCANCELAR;
    private javax.swing.JButton jButtonGUARDAR;
    private javax.swing.JButton jButtonVerAutores;
    private javax.swing.JComboBox jComboBoxPaisOrigen;
    private javax.swing.JLabel jLabelAPELLDIO;
    private javax.swing.JLabel jLabelNOMBRE;
    private javax.swing.JLabel jLabelPAISDEORIGEN;
    private javax.swing.JTextField jTextFieldAPELLIDO;
    private javax.swing.JTextField jTextFieldNOMBRES;
    // End of variables declaration//GEN-END:variables
}
