/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Frame;
import javax.swing.JFrame;

/**
 *
 * @author Alex
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setTitle("VENTANA PRINCIPAL");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBarBARRAPRINCIPAL = new javax.swing.JMenuBar();
        jMenuAutor = new javax.swing.JMenu();
        jMenuItemNUEVO = new javax.swing.JMenuItem();
        jMenuItemBUSCAR = new javax.swing.JMenuItem();
        jMenuLIBRO = new javax.swing.JMenu();
        AYUDA = new javax.swing.JMenu();
        jMenuItemSALIR = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Principal");

        jMenuAutor.setText("Autor");

        jMenuItemNUEVO.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemNUEVO.setText("Nuevo");
        jMenuItemNUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNUEVOActionPerformed(evt);
            }
        });
        jMenuAutor.add(jMenuItemNUEVO);

        jMenuItemBUSCAR.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemBUSCAR.setText("Buscar");
        jMenuAutor.add(jMenuItemBUSCAR);

        jMenuBarBARRAPRINCIPAL.add(jMenuAutor);

        jMenuLIBRO.setText("Libro");
        jMenuBarBARRAPRINCIPAL.add(jMenuLIBRO);

        AYUDA.setText("Ayuda");

        jMenuItemSALIR.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemSALIR.setText("Salir");
        AYUDA.add(jMenuItemSALIR);

        jMenuBarBARRAPRINCIPAL.add(AYUDA);

        setJMenuBar(jMenuBarBARRAPRINCIPAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNUEVOActionPerformed
    
        
        JFrameNuevoAutor jfNuevoAutor = new JFrameNuevoAutor();
        jfNuevoAutor.setVisible(true);
        
        
        
    }//GEN-LAST:event_jMenuItemNUEVOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AYUDA;
    private javax.swing.JMenu jMenuAutor;
    private javax.swing.JMenuBar jMenuBarBARRAPRINCIPAL;
    private javax.swing.JMenuItem jMenuItemBUSCAR;
    private javax.swing.JMenuItem jMenuItemNUEVO;
    private javax.swing.JMenuItem jMenuItemSALIR;
    private javax.swing.JMenu jMenuLIBRO;
    // End of variables declaration//GEN-END:variables
}
